Feature/bingo game
Portkey-Wallet/portkey-indexer pull request #9
Opened 2023-06-01 02:10 UTC by xibo1

2023-06-12 08:30 UTC, lip-w approved these changes

2023-06-16 10:17 UTC, gldeng requested changes

2023-06-16 10:17 UTC, gldeng commented on src/Portkey.Indexer.CA/Processors/BingoedProcessor.cs
> +        await CAHolderTransactionIndexRepository.AddOrUpdateAsync(transIndex);
Why do we update another index here?

2023-06-16 10:21 UTC, gldeng commented
@xibo1 Same issues for all 3 processors.

2023-06-16 10:21 UTC, gldeng commented
@xibo1 @kevin00k Can you split the PR into two? It makes sense to separate them.

2023-06-20 07:15 UTC, xiboXD commented on src/Portkey.Indexer.CA/Processors/PlayedProcessor.cs
> +    private readonly IAElfIndexerClientEntityRepository<CAHolderIndex, LogEventInfo> _repository;
OK，removed in BingoGame Index

2023-06-20 07:17 UTC, xiboXD commented on src/Portkey.Indexer.CA/Processors/PlayedProcessor.cs
> +public class PlayedProcessor : CAHolderTransactionProcessorBase<Played>
In BingoGame indexer, it will inherit BingoGameProcessorBase, it's a more suitable base for bingo game

2023-06-20 07:26 UTC, xiboXD commented on src/Portkey.Indexer.CA/Processors/BingoedProcessor.cs
> +        await CAHolderTransactionIndexRepository.AddOrUpdateAsync(transIndex);
Deleted in BingoGame indexer

2023-07-06 07:40 UTC, merged